# Default Application Configuration
# Use 'dev' profile for H2 development, 'prod' profile for PostgreSQL production

spring:
  profiles:
    active: dev  # Default to development profile

---
# Production Profile - PostgreSQL Database
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/xmpp
    username: xmpp_user
    password: xmpp_pass
    pool:
      initial-size: 10
      max-size: 50
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

---
# Common Configuration (applies to all profiles)
server:
  port: 8080

# XMPP Server Configuration
xmpp:
  server:
    port: 5222
    domain: localhost
    timeout-minutes: 30
    max-connections: 10000
  
  # Security settings
  security:
    tls:
      # Enable TLS support (default: true)
      enabled: true
      
      # Require TLS for all connections (default: true)
      # If false, TLS is optional and clients can connect without encryption
      required: true
      
      # Keystore configuration
      keystore-path: classpath:keystore.jks
      keystore-password: changeit
      keystore-type: JKS
      
      # TLS protocol versions to support
      supported-protocols:
        - TLSv1.2
        - TLSv1.3
      
      # TLS cipher suites (empty = use JVM defaults)
      supported-cipher-suites: []
      
      # Client certificate verification
      client-auth: none  # Options: none, want, need
      
    sasl:
      mechanisms:
        - PLAIN
        - SCRAM-SHA-1
        - SCRAM-SHA-256

# Logging Configuration
logging:
  level:
    io.github.koosty.xmpp: DEBUG
    reactor.netty: INFO
    io.r2dbc.postgresql: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"